/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DocumentMetadata = IDL.Record({
  'id' : IDL.Text,
  'listingId' : IDL.Text,
  'blobRef' : ExternalBlob,
  'fileName' : IDL.Text,
  'isPublic' : IDL.Bool,
  'docType' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const PropertyHistory = IDL.Record({
  'id' : IDL.Text,
  'listingId' : IDL.Text,
  'createdAt' : IDL.Int,
  'year' : IDL.Nat,
  'previousOwner' : IDL.Text,
  'event' : IDL.Text,
  'currentOwner' : IDL.Text,
});
export const SoilReport = IDL.Record({
  'id' : IDL.Text,
  'soilType' : IDL.Text,
  'listingId' : IDL.Text,
  'floodRisk' : IDL.Text,
  'reportDate' : IDL.Int,
  'waterLogging' : IDL.Text,
  'reportedBy' : IDL.Text,
  'notes' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LandListing = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'sellerWhatsapp' : IDL.Text,
  'sellerPhone' : IDL.Text,
  'pricePerDecimal' : IDL.Nat,
  'area' : IDL.Float64,
  'roadAccess' : IDL.Text,
  'createdAt' : IDL.Int,
  'division' : IDL.Text,
  'description' : IDL.Text,
  'district' : IDL.Text,
  'verifiedBadge' : IDL.Text,
  'sellerName' : IDL.Text,
  'updatedAt' : IDL.Int,
  'isVerified' : IDL.Bool,
  'isFeatured' : IDL.Bool,
  'address' : IDL.Text,
  'landType' : IDL.Text,
  'sellerId' : IDL.Text,
  'price' : IDL.Nat,
  'roadWidth' : IDL.Text,
  'upazila' : IDL.Text,
  'orientation' : IDL.Text,
});
export const Lawyer = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'updatedAt' : IDL.Int,
  'specialization' : IDL.Text,
  'phone' : IDL.Text,
  'consultationFee' : IDL.Nat,
  'location' : IDL.Text,
});
export const NewsArticle = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'createdAt' : IDL.Int,
  'publishedAt' : IDL.Int,
  'author' : IDL.Text,
  'updatedAt' : IDL.Int,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const DocumentAccessRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'requester' : IDL.Text,
  'listingId' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const Offer = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'counterPrice' : IDL.Opt(IDL.Nat),
  'counterMessage' : IDL.Opt(IDL.Text),
  'listingId' : IDL.Text,
  'createdAt' : IDL.Int,
  'buyerPhone' : IDL.Text,
  'updatedAt' : IDL.Int,
  'offerPrice' : IDL.Nat,
  'message' : IDL.Text,
  'buyerId' : IDL.Text,
  'buyerName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDocumentMetadata' : IDL.Func([DocumentMetadata], [], []),
  'addPropertyHistory' : IDL.Func([PropertyHistory], [], []),
  'addSoilReport' : IDL.Func([SoilReport], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'counterOffer' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'createLandListing' : IDL.Func([LandListing], [], []),
  'createLawyer' : IDL.Func([Lawyer], [], []),
  'createNewsArticle' : IDL.Func([NewsArticle], [], []),
  'deleteLandListing' : IDL.Func([IDL.Text], [], []),
  'deleteLawyer' : IDL.Func([IDL.Text], [], []),
  'deleteNewsArticle' : IDL.Func([IDL.Text], [], []),
  'getAccessibleDocuments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DocumentMetadata)],
      ['query'],
    ),
  'getAllLandListings' : IDL.Func([], [IDL.Vec(LandListing)], ['query']),
  'getAllLawyers' : IDL.Func([], [IDL.Vec(Lawyer)], ['query']),
  'getAllNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getAllPublishedNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocumentAccessRequests' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DocumentAccessRequest)],
      ['query'],
    ),
  'getFeaturedListings' : IDL.Func([], [IDL.Vec(LandListing)], ['query']),
  'getLandListing' : IDL.Func([IDL.Text], [IDL.Opt(LandListing)], ['query']),
  'getLawyer' : IDL.Func([IDL.Text], [IDL.Opt(Lawyer)], ['query']),
  'getNewsArticle' : IDL.Func([IDL.Text], [IDL.Opt(NewsArticle)], ['query']),
  'getOffersByBuyer' : IDL.Func([IDL.Text], [IDL.Vec(Offer)], ['query']),
  'getOffersByListing' : IDL.Func([IDL.Text], [IDL.Vec(Offer)], ['query']),
  'getPropertyHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PropertyHistory)],
      ['query'],
    ),
  'getSoilReport' : IDL.Func([IDL.Text], [IDL.Opt(SoilReport)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantDocumentAccess' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'requestDocumentAccess' : IDL.Func([DocumentAccessRequest], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchListings' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Vec(LandListing)],
      ['query'],
    ),
  'submitOffer' : IDL.Func([Offer], [], []),
  'toggleFeaturedListing' : IDL.Func([IDL.Text], [], []),
  'updateLandListing' : IDL.Func([LandListing], [], []),
  'updateLawyer' : IDL.Func([Lawyer], [], []),
  'updateNewsArticle' : IDL.Func([NewsArticle], [], []),
  'updateOfferStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateSoilReport' : IDL.Func([SoilReport], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DocumentMetadata = IDL.Record({
    'id' : IDL.Text,
    'listingId' : IDL.Text,
    'blobRef' : ExternalBlob,
    'fileName' : IDL.Text,
    'isPublic' : IDL.Bool,
    'docType' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const PropertyHistory = IDL.Record({
    'id' : IDL.Text,
    'listingId' : IDL.Text,
    'createdAt' : IDL.Int,
    'year' : IDL.Nat,
    'previousOwner' : IDL.Text,
    'event' : IDL.Text,
    'currentOwner' : IDL.Text,
  });
  const SoilReport = IDL.Record({
    'id' : IDL.Text,
    'soilType' : IDL.Text,
    'listingId' : IDL.Text,
    'floodRisk' : IDL.Text,
    'reportDate' : IDL.Int,
    'waterLogging' : IDL.Text,
    'reportedBy' : IDL.Text,
    'notes' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LandListing = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'sellerWhatsapp' : IDL.Text,
    'sellerPhone' : IDL.Text,
    'pricePerDecimal' : IDL.Nat,
    'area' : IDL.Float64,
    'roadAccess' : IDL.Text,
    'createdAt' : IDL.Int,
    'division' : IDL.Text,
    'description' : IDL.Text,
    'district' : IDL.Text,
    'verifiedBadge' : IDL.Text,
    'sellerName' : IDL.Text,
    'updatedAt' : IDL.Int,
    'isVerified' : IDL.Bool,
    'isFeatured' : IDL.Bool,
    'address' : IDL.Text,
    'landType' : IDL.Text,
    'sellerId' : IDL.Text,
    'price' : IDL.Nat,
    'roadWidth' : IDL.Text,
    'upazila' : IDL.Text,
    'orientation' : IDL.Text,
  });
  const Lawyer = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'updatedAt' : IDL.Int,
    'specialization' : IDL.Text,
    'phone' : IDL.Text,
    'consultationFee' : IDL.Nat,
    'location' : IDL.Text,
  });
  const NewsArticle = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'createdAt' : IDL.Int,
    'publishedAt' : IDL.Int,
    'author' : IDL.Text,
    'updatedAt' : IDL.Int,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const DocumentAccessRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'requester' : IDL.Text,
    'listingId' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const Offer = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'counterPrice' : IDL.Opt(IDL.Nat),
    'counterMessage' : IDL.Opt(IDL.Text),
    'listingId' : IDL.Text,
    'createdAt' : IDL.Int,
    'buyerPhone' : IDL.Text,
    'updatedAt' : IDL.Int,
    'offerPrice' : IDL.Nat,
    'message' : IDL.Text,
    'buyerId' : IDL.Text,
    'buyerName' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDocumentMetadata' : IDL.Func([DocumentMetadata], [], []),
    'addPropertyHistory' : IDL.Func([PropertyHistory], [], []),
    'addSoilReport' : IDL.Func([SoilReport], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'counterOffer' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'createLandListing' : IDL.Func([LandListing], [], []),
    'createLawyer' : IDL.Func([Lawyer], [], []),
    'createNewsArticle' : IDL.Func([NewsArticle], [], []),
    'deleteLandListing' : IDL.Func([IDL.Text], [], []),
    'deleteLawyer' : IDL.Func([IDL.Text], [], []),
    'deleteNewsArticle' : IDL.Func([IDL.Text], [], []),
    'getAccessibleDocuments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DocumentMetadata)],
        ['query'],
      ),
    'getAllLandListings' : IDL.Func([], [IDL.Vec(LandListing)], ['query']),
    'getAllLawyers' : IDL.Func([], [IDL.Vec(Lawyer)], ['query']),
    'getAllNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getAllPublishedNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocumentAccessRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DocumentAccessRequest)],
        ['query'],
      ),
    'getFeaturedListings' : IDL.Func([], [IDL.Vec(LandListing)], ['query']),
    'getLandListing' : IDL.Func([IDL.Text], [IDL.Opt(LandListing)], ['query']),
    'getLawyer' : IDL.Func([IDL.Text], [IDL.Opt(Lawyer)], ['query']),
    'getNewsArticle' : IDL.Func([IDL.Text], [IDL.Opt(NewsArticle)], ['query']),
    'getOffersByBuyer' : IDL.Func([IDL.Text], [IDL.Vec(Offer)], ['query']),
    'getOffersByListing' : IDL.Func([IDL.Text], [IDL.Vec(Offer)], ['query']),
    'getPropertyHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PropertyHistory)],
        ['query'],
      ),
    'getSoilReport' : IDL.Func([IDL.Text], [IDL.Opt(SoilReport)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantDocumentAccess' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'requestDocumentAccess' : IDL.Func([DocumentAccessRequest], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchListings' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Vec(LandListing)],
        ['query'],
      ),
    'submitOffer' : IDL.Func([Offer], [], []),
    'toggleFeaturedListing' : IDL.Func([IDL.Text], [], []),
    'updateLandListing' : IDL.Func([LandListing], [], []),
    'updateLawyer' : IDL.Func([Lawyer], [], []),
    'updateNewsArticle' : IDL.Func([NewsArticle], [], []),
    'updateOfferStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateSoilReport' : IDL.Func([SoilReport], [], []),
  });
};

export const init = ({ IDL }) => { return []; };