/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DocumentAccessRequest {
  'id' : string,
  'status' : string,
  'requester' : string,
  'listingId' : string,
  'createdAt' : bigint,
}
export interface DocumentMetadata {
  'id' : string,
  'listingId' : string,
  'blobRef' : ExternalBlob,
  'fileName' : string,
  'isPublic' : boolean,
  'docType' : string,
  'uploadedAt' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface LandListing {
  'id' : string,
  'status' : string,
  'title' : string,
  'sellerWhatsapp' : string,
  'sellerPhone' : string,
  'pricePerDecimal' : bigint,
  'area' : number,
  'roadAccess' : string,
  'createdAt' : bigint,
  'division' : string,
  'description' : string,
  'district' : string,
  'verifiedBadge' : string,
  'sellerName' : string,
  'updatedAt' : bigint,
  'isVerified' : boolean,
  'isFeatured' : boolean,
  'address' : string,
  'landType' : string,
  'sellerId' : string,
  'price' : bigint,
  'roadWidth' : string,
  'upazila' : string,
  'orientation' : string,
}
export interface Lawyer {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'isAvailable' : boolean,
  'description' : string,
  'email' : string,
  'updatedAt' : bigint,
  'specialization' : string,
  'phone' : string,
  'consultationFee' : bigint,
  'location' : string,
}
export interface NewsArticle {
  'id' : string,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'createdAt' : bigint,
  'publishedAt' : bigint,
  'author' : string,
  'updatedAt' : bigint,
  'category' : string,
}
export interface Offer {
  'id' : string,
  'status' : string,
  'counterPrice' : [] | [bigint],
  'counterMessage' : [] | [string],
  'listingId' : string,
  'createdAt' : bigint,
  'buyerPhone' : string,
  'updatedAt' : bigint,
  'offerPrice' : bigint,
  'message' : string,
  'buyerId' : string,
  'buyerName' : string,
}
export interface PropertyHistory {
  'id' : string,
  'listingId' : string,
  'createdAt' : bigint,
  'year' : bigint,
  'previousOwner' : string,
  'event' : string,
  'currentOwner' : string,
}
export interface SoilReport {
  'id' : string,
  'soilType' : string,
  'listingId' : string,
  'floodRisk' : string,
  'reportDate' : bigint,
  'waterLogging' : string,
  'reportedBy' : string,
  'notes' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDocumentMetadata' : ActorMethod<[DocumentMetadata], undefined>,
  'addPropertyHistory' : ActorMethod<[PropertyHistory], undefined>,
  'addSoilReport' : ActorMethod<[SoilReport], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'counterOffer' : ActorMethod<[string, bigint, string], undefined>,
  'createLandListing' : ActorMethod<[LandListing], undefined>,
  'createLawyer' : ActorMethod<[Lawyer], undefined>,
  'createNewsArticle' : ActorMethod<[NewsArticle], undefined>,
  'deleteLandListing' : ActorMethod<[string], undefined>,
  'deleteLawyer' : ActorMethod<[string], undefined>,
  'deleteNewsArticle' : ActorMethod<[string], undefined>,
  'getAccessibleDocuments' : ActorMethod<[string], Array<DocumentMetadata>>,
  'getAllLandListings' : ActorMethod<[], Array<LandListing>>,
  'getAllLawyers' : ActorMethod<[], Array<Lawyer>>,
  'getAllNews' : ActorMethod<[], Array<NewsArticle>>,
  'getAllPublishedNews' : ActorMethod<[], Array<NewsArticle>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocumentAccessRequests' : ActorMethod<
    [string],
    Array<DocumentAccessRequest>
  >,
  'getFeaturedListings' : ActorMethod<[], Array<LandListing>>,
  'getLandListing' : ActorMethod<[string], [] | [LandListing]>,
  'getLawyer' : ActorMethod<[string], [] | [Lawyer]>,
  'getNewsArticle' : ActorMethod<[string], [] | [NewsArticle]>,
  'getOffersByBuyer' : ActorMethod<[string], Array<Offer>>,
  'getOffersByListing' : ActorMethod<[string], Array<Offer>>,
  'getPropertyHistory' : ActorMethod<[string], Array<PropertyHistory>>,
  'getSoilReport' : ActorMethod<[string], [] | [SoilReport]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantDocumentAccess' : ActorMethod<[string, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'requestDocumentAccess' : ActorMethod<[DocumentAccessRequest], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchListings' : ActorMethod<
    [string, string, string, bigint, bigint, string],
    Array<LandListing>
  >,
  'submitOffer' : ActorMethod<[Offer], undefined>,
  'toggleFeaturedListing' : ActorMethod<[string], undefined>,
  'updateLandListing' : ActorMethod<[LandListing], undefined>,
  'updateLawyer' : ActorMethod<[Lawyer], undefined>,
  'updateNewsArticle' : ActorMethod<[NewsArticle], undefined>,
  'updateOfferStatus' : ActorMethod<[string, string], undefined>,
  'updateSoilReport' : ActorMethod<[SoilReport], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];