/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PropertyHistory {
    id: string;
    listingId: string;
    createdAt: bigint;
    year: bigint;
    previousOwner: string;
    event: string;
    currentOwner: string;
}
export interface SoilReport {
    id: string;
    soilType: string;
    listingId: string;
    floodRisk: string;
    reportDate: bigint;
    waterLogging: string;
    reportedBy: string;
    notes: string;
}
export interface LandListing {
    id: string;
    status: string;
    title: string;
    sellerWhatsapp: string;
    sellerPhone: string;
    pricePerDecimal: bigint;
    area: number;
    roadAccess: string;
    createdAt: bigint;
    division: string;
    description: string;
    district: string;
    verifiedBadge: string;
    sellerName: string;
    updatedAt: bigint;
    isVerified: boolean;
    isFeatured: boolean;
    address: string;
    landType: string;
    sellerId: string;
    price: bigint;
    roadWidth: string;
    upazila: string;
    orientation: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface DocumentMetadata {
    id: string;
    listingId: string;
    blobRef: ExternalBlob;
    fileName: string;
    isPublic: boolean;
    docType: string;
    uploadedAt: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Lawyer {
    id: string;
    name: string;
    createdAt: bigint;
    isAvailable: boolean;
    description: string;
    email: string;
    updatedAt: bigint;
    specialization: string;
    phone: string;
    consultationFee: bigint;
    location: string;
}
export interface DocumentAccessRequest {
    id: string;
    status: string;
    requester: string;
    listingId: string;
    createdAt: bigint;
}
export interface Offer {
    id: string;
    status: string;
    counterPrice?: bigint;
    counterMessage?: string;
    listingId: string;
    createdAt: bigint;
    buyerPhone: string;
    updatedAt: bigint;
    offerPrice: bigint;
    message: string;
    buyerId: string;
    buyerName: string;
}
export interface NewsArticle {
    id: string;
    title: string;
    content: string;
    isPublished: boolean;
    createdAt: bigint;
    publishedAt: bigint;
    author: string;
    updatedAt: bigint;
    category: string;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
    location: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDocumentMetadata(metadata: DocumentMetadata): Promise<void>;
    addPropertyHistory(history: PropertyHistory): Promise<void>;
    addSoilReport(report: SoilReport): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    counterOffer(id: string, counterPrice: bigint, counterMessage: string): Promise<void>;
    createLandListing(listing: LandListing): Promise<void>;
    createLawyer(lawyer: Lawyer): Promise<void>;
    createNewsArticle(article: NewsArticle): Promise<void>;
    deleteLandListing(id: string): Promise<void>;
    deleteLawyer(id: string): Promise<void>;
    deleteNewsArticle(id: string): Promise<void>;
    getAccessibleDocuments(listingId: string): Promise<Array<DocumentMetadata>>;
    getAllLandListings(): Promise<Array<LandListing>>;
    getAllLawyers(): Promise<Array<Lawyer>>;
    getAllNews(): Promise<Array<NewsArticle>>;
    getAllPublishedNews(): Promise<Array<NewsArticle>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDocumentAccessRequests(listingId: string): Promise<Array<DocumentAccessRequest>>;
    getFeaturedListings(): Promise<Array<LandListing>>;
    getLandListing(id: string): Promise<LandListing | null>;
    getLawyer(id: string): Promise<Lawyer | null>;
    getNewsArticle(id: string): Promise<NewsArticle | null>;
    getOffersByBuyer(buyerId: string): Promise<Array<Offer>>;
    getOffersByListing(listingId: string): Promise<Array<Offer>>;
    getPropertyHistory(listingId: string): Promise<Array<PropertyHistory>>;
    getSoilReport(listingId: string): Promise<SoilReport | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    grantDocumentAccess(requestId: string, status: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    requestDocumentAccess(request: DocumentAccessRequest): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchListings(division: string, district: string, upazila: string, minPrice: bigint, maxPrice: bigint, landType: string): Promise<Array<LandListing>>;
    submitOffer(offer: Offer): Promise<void>;
    toggleFeaturedListing(id: string): Promise<void>;
    updateLandListing(listing: LandListing): Promise<void>;
    updateLawyer(lawyer: Lawyer): Promise<void>;
    updateNewsArticle(article: NewsArticle): Promise<void>;
    updateOfferStatus(id: string, status: string): Promise<void>;
    updateSoilReport(report: SoilReport): Promise<void>;
}
import type { DocumentMetadata as _DocumentMetadata, ExternalBlob as _ExternalBlob, LandListing as _LandListing, Lawyer as _Lawyer, NewsArticle as _NewsArticle, Offer as _Offer, SoilReport as _SoilReport, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDocumentMetadata(arg0: DocumentMetadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDocumentMetadata(await to_candid_DocumentMetadata_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDocumentMetadata(await to_candid_DocumentMetadata_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPropertyHistory(arg0: PropertyHistory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPropertyHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPropertyHistory(arg0);
            return result;
        }
    }
    async addSoilReport(arg0: SoilReport): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSoilReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSoilReport(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async counterOffer(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.counterOffer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.counterOffer(arg0, arg1, arg2);
            return result;
        }
    }
    async createLandListing(arg0: LandListing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createLandListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLandListing(arg0);
            return result;
        }
    }
    async createLawyer(arg0: Lawyer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createLawyer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLawyer(arg0);
            return result;
        }
    }
    async createNewsArticle(arg0: NewsArticle): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createNewsArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNewsArticle(arg0);
            return result;
        }
    }
    async deleteLandListing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLandListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLandListing(arg0);
            return result;
        }
    }
    async deleteLawyer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLawyer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLawyer(arg0);
            return result;
        }
    }
    async deleteNewsArticle(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNewsArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNewsArticle(arg0);
            return result;
        }
    }
    async getAccessibleDocuments(arg0: string): Promise<Array<DocumentMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccessibleDocuments(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccessibleDocuments(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLandListings(): Promise<Array<LandListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLandListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLandListings();
            return result;
        }
    }
    async getAllLawyers(): Promise<Array<Lawyer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLawyers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLawyers();
            return result;
        }
    }
    async getAllNews(): Promise<Array<NewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNews();
            return result;
        }
    }
    async getAllPublishedNews(): Promise<Array<NewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublishedNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublishedNews();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocumentAccessRequests(arg0: string): Promise<Array<DocumentAccessRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentAccessRequests(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentAccessRequests(arg0);
            return result;
        }
    }
    async getFeaturedListings(): Promise<Array<LandListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedListings();
            return result;
        }
    }
    async getLandListing(arg0: string): Promise<LandListing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLandListing(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLandListing(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLawyer(arg0: string): Promise<Lawyer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLawyer(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLawyer(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsArticle(arg0: string): Promise<NewsArticle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsArticle(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsArticle(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOffersByBuyer(arg0: string): Promise<Array<Offer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOffersByBuyer(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOffersByBuyer(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOffersByListing(arg0: string): Promise<Array<Offer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOffersByListing(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOffersByListing(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropertyHistory(arg0: string): Promise<Array<PropertyHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertyHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertyHistory(arg0);
            return result;
        }
    }
    async getSoilReport(arg0: string): Promise<SoilReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSoilReport(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSoilReport(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async grantDocumentAccess(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantDocumentAccess(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantDocumentAccess(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async requestDocumentAccess(arg0: DocumentAccessRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestDocumentAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestDocumentAccess(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchListings(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: string): Promise<Array<LandListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchListings(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchListings(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async submitOffer(arg0: Offer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOffer(to_candid_Offer_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOffer(to_candid_Offer_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async toggleFeaturedListing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFeaturedListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFeaturedListing(arg0);
            return result;
        }
    }
    async updateLandListing(arg0: LandListing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLandListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLandListing(arg0);
            return result;
        }
    }
    async updateLawyer(arg0: Lawyer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLawyer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLawyer(arg0);
            return result;
        }
    }
    async updateNewsArticle(arg0: NewsArticle): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNewsArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNewsArticle(arg0);
            return result;
        }
    }
    async updateOfferStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOfferStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOfferStatus(arg0, arg1);
            return result;
        }
    }
    async updateSoilReport(arg0: SoilReport): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSoilReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSoilReport(arg0);
            return result;
        }
    }
}
async function from_candid_DocumentMetadata_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentMetadata): Promise<DocumentMetadata> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Offer_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Offer): Offer {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LandListing]): LandListing | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Lawyer]): Lawyer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NewsArticle]): NewsArticle | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SoilReport]): SoilReport | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    listingId: string;
    blobRef: _ExternalBlob;
    fileName: string;
    isPublic: boolean;
    docType: string;
    uploadedAt: bigint;
}): Promise<{
    id: string;
    listingId: string;
    blobRef: ExternalBlob;
    fileName: string;
    isPublic: boolean;
    docType: string;
    uploadedAt: bigint;
}> {
    return {
        id: value.id,
        listingId: value.listingId,
        blobRef: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.blobRef),
        fileName: value.fileName,
        isPublic: value.isPublic,
        docType: value.docType,
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    counterPrice: [] | [bigint];
    counterMessage: [] | [string];
    listingId: string;
    createdAt: bigint;
    buyerPhone: string;
    updatedAt: bigint;
    offerPrice: bigint;
    message: string;
    buyerId: string;
    buyerName: string;
}): {
    id: string;
    status: string;
    counterPrice?: bigint;
    counterMessage?: string;
    listingId: string;
    createdAt: bigint;
    buyerPhone: string;
    updatedAt: bigint;
    offerPrice: bigint;
    message: string;
    buyerId: string;
    buyerName: string;
} {
    return {
        id: value.id,
        status: value.status,
        counterPrice: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.counterPrice)),
        counterMessage: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.counterMessage)),
        listingId: value.listingId,
        createdAt: value.createdAt,
        buyerPhone: value.buyerPhone,
        updatedAt: value.updatedAt,
        offerPrice: value.offerPrice,
        message: value.message,
        buyerId: value.buyerId,
        buyerName: value.buyerName
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DocumentMetadata>): Promise<Array<DocumentMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DocumentMetadata_n14(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Offer>): Array<Offer> {
    return value.map((x)=>from_candid_Offer_n24(_uploadFile, _downloadFile, x));
}
async function to_candid_DocumentMetadata_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentMetadata): Promise<_DocumentMetadata> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Offer_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Offer): _Offer {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    counterPrice?: bigint;
    counterMessage?: string;
    listingId: string;
    createdAt: bigint;
    buyerPhone: string;
    updatedAt: bigint;
    offerPrice: bigint;
    message: string;
    buyerId: string;
    buyerName: string;
}): {
    id: string;
    status: string;
    counterPrice: [] | [bigint];
    counterMessage: [] | [string];
    listingId: string;
    createdAt: bigint;
    buyerPhone: string;
    updatedAt: bigint;
    offerPrice: bigint;
    message: string;
    buyerId: string;
    buyerName: string;
} {
    return {
        id: value.id,
        status: value.status,
        counterPrice: value.counterPrice ? candid_some(value.counterPrice) : candid_none(),
        counterMessage: value.counterMessage ? candid_some(value.counterMessage) : candid_none(),
        listingId: value.listingId,
        createdAt: value.createdAt,
        buyerPhone: value.buyerPhone,
        updatedAt: value.updatedAt,
        offerPrice: value.offerPrice,
        message: value.message,
        buyerId: value.buyerId,
        buyerName: value.buyerName
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    listingId: string;
    blobRef: ExternalBlob;
    fileName: string;
    isPublic: boolean;
    docType: string;
    uploadedAt: bigint;
}): Promise<{
    id: string;
    listingId: string;
    blobRef: _ExternalBlob;
    fileName: string;
    isPublic: boolean;
    docType: string;
    uploadedAt: bigint;
}> {
    return {
        id: value.id,
        listingId: value.listingId,
        blobRef: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.blobRef),
        fileName: value.fileName,
        isPublic: value.isPublic,
        docType: value.docType,
        uploadedAt: value.uploadedAt
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
